### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zqm64** [adrian1234a/android_vendor_xiaomi_ugg#1]
[ 41% 3932/9484] Building with Jack: /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/classes.dex
FAILED: /bin/bash -c "(rm -f /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/classes.dex ) && (rm -f /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/classes.jack ) && (rm -rf /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc ) && (mkdir -p /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/ ) && (mkdir -p /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/ ) && (mkdir -p /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc ) && (rm -f /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list ) && (touch /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list ) && (echo -n 'packages/providers/MediaProvider/src/com/android/providers/media/MediaDocumentsProvider.java packages/providers/MediaProvider/src/com/android/providers/media/MediaProvider.java packages/providers/MediaProvider/src/com/android/providers/media/MediaScannerReceiver.java packages/providers/MediaProvider/src/com/android/providers/media/MediaScannerService.java packages/providers/MediaProvider/src/com/android/providers/media/MediaThumbRequest.java packages/providers/MediaProvider/src/com/android/providers/media/MediaUpgradeReceiver.java packages/providers/MediaProvider/src/com/android/providers/media/MtpReceiver.java packages/providers/MediaProvider/src/com/android/providers/media/MtpService.java packages/providers/MediaProvider/src/com/android/providers/media/RingtonePickerActivity.java /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/src/src/com/android/providers/media/IMtpService.java ' >> /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list ) && (if [ -d \"/mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/src\" ]; then find /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/src -name '*.java' >> /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list; fi ) && (tr ' ' '\\n' < /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list | build/tools/normalize_path.py | sort -u > /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list-uniq ) && (echo -basedirectory /mnt/data/0/build/rr-n > /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/classes.dex.flags; echo -forceprocessing -include build/core/proguard.flags -dontobfuscate -dontoptimize -printmapping /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack_dictionary -include /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/proguard_options -include /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/proguard_options   >> /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/classes.dex.flags ) && (if [ -s /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list-uniq ] ; then export tmpEcjArg=\"@/mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list-uniq\"; else export tmpEcjArg=\"\"; fi;  JACK_VERSION=3.36.CANDIDATE /mnt/data/0/build/rr-n/out/host/linux-x86/bin/jack @build/core/jack-default.args --verbose error -g -D jack.java.source.version=1.8    --classpath /mnt/data/0/build/rr-n/out/target/common/obj/JAVA_LIBRARIES/core-junit_intermediates/classes.jack:/mnt/data/0/build/rr-n/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes.jack:/mnt/data/0/build/rr-n/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes.jack:/mnt/data/0/build/rr-n/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes.jack:/mnt/data/0/build/rr-n/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes.jack:/mnt/data/0/build/rr-n/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes.jack   -D jack.android.min-api-level=25 -D jack.import.resource.policy=keep-first -D jack.import.type.policy=keep-first --output-jack /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/classes.jack  --output-dex /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc  --config-proguard /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/classes.dex.flags \$tmpEcjArg || ( rm -rf /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/classes.jack; exit 41 ) ) && (mv /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/classes*.dex /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/with-local/ ) && (rm -f /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list ) && (mv /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc/java-source-list-uniq /mnt/data/0/build/rr-n/out/target/common/obj/APPS/MediaProvider_intermediates/jack-rsc.java-source-list )"
**ERROR: /home/build/data-0/rr-n/packages/providers/MediaProvider/src/com/android/providers/media/MediaProvider.java:4300: The method eraseMiniThumb(long) is undefined for the type MiniThumbFile
ERROR: /home/build/data-0/rr-n/packages/providers/MediaProvider/src/com/android/providers/media/MediaProvider.java:4325: The method eraseMiniThumb(long) is undefined for the type MiniThumbFile
ERROR: /home/build/data-0/rr-n/packages/providers/MediaProvider/src/com/android/providers/media/MediaProvider.java:4516: The method eraseMiniThumb(long) is undefined for the type MiniThumbFile**

**Comment by zqm64** [comment]
Oh, i posted it wrong, it should be posted in device tree

**Comment by adrian1234a** [comment]
Don't worry sync this: https://github.com/Mbtt107/android_packages_providers_MediaProvider

**Comment by zqm64** [comment]
(first of all, sorry for my bad english)
Ok. You can consider creating local_manifests just like other developers. One more thing, do you need my server? I can provide it to you 
to build roms for free.

**Comment by adrian1234a** [comment]
Sure

**Comment by zqm64** [comment]
so how to contact you

**Comment by adrian1234a** [comment]
On my telegram: @adrian1234a
